{
 "title": "ShardLeak",
 "tags": [ "shardleak" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(shardleak_requests_total[1m])) by (algorithm)",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(shardleak_request_duration_seconds_bucket[1m])) by (le, algorithm))",
     "legendFormat": "p95 {{algorithm}}"
    }
   ]
  },
  {
   "title": "Allowed / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(shardleak_allowed_total[1m])) by (algorithm)",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(shardleak_request_duration_seconds_bucket[1m])) by (le, algorithm))",
     "legendFormat": "p99 {{algorithm}}"
    }
   ]
  },
  {
   "title": "Rejected / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(shardleak_rejected_total[1m])) by (algorithm)",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "Redis Errors / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(shardleak_redis_errors_total[1m])",
     "legendFormat": "Redis errors"
    }
   ]
  },
  {
   "title": "DB Errors / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(shardleak_db_errors_total[1m])",
     "legendFormat": "DB errors"
    }
   ]
  }
 ]
}